### ISSUE TITLE
Migrate to tensorflow v1.3

### ISSUE THREAD

**Issue by qinyao-he** [qinyao-he/bit-rnn#4]
Currently only support tf v0.12 and have problem when running on tf v1.0 and above due to changes in interfaces.

**Comment by RadZaeem** [comment]
what errors do you bump into?

**Comment by RadZaeem** [comment]
I haven't properly forked it but, you can download from my ml-testbed repo
I managed to get it working for Tensorflow 1.3, but it mysteriously gained 130 perplexity (from paper, 150 perplexity).
I modified reader.py, train.py, bit_rnn_cell.py and model.py
- combined old reader.py with newer reader.py from TF 1.3 tutorial for PTB
- fixed tf.split and tf.concat argument order
- in bit_rnn_cell.py, added from tensorflow.python.ops import rnn_cell_impl, to use _linear
https://github.com/RadZaeem/ml-testbed

**Comment by qinyao-he** [comment]
@RadZaeem I have unsuccessfully reproduced your result of 130 perplexity using your code. How many epochs have you run?

**Comment by RadZaeem** [comment]
Sorry for late reply.
That 130 result was previous commit. My bad. That 130 perplexity was due to I didn't change "Matrix" to "kernel" in bit_rnn_cell.py. The code skipped quantization for weights resulting reduced perplexity. This is naming change for TF 1.x
I reran the corrected code (current commit, probably that you downloaded) and got Test Perplexity: 151.020

btw should the biases ("bias" variables) also need to be quantized?

**Comment by qinyao-he** [comment]
@RadZaeem In our consideration, quantization of bias of usually not needed in all popular approaches, since we mainly want to reduce the computational cost of matrix multiplication rather than elementwise operation, which cost much less.

**Comment by qinyao-he** [comment]
@RadZaeem Also, the output of bit matrix product is a usual real number, not able to do bitwise operation with respect to quantized bias.

**Comment by RadZaeem** [comment]
@hqythu Ok thanks for clarification.
